spring:
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://host.docker.internal:3306/oscboard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # ???? ?? ??? ?? k8s? ??? ? ??? ?? ?? mysql? ??
    #    url: jdbc:mysql://localhost:3306/oscboard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #     k3d ???? ??
    url: jdbc:mysql://localhost:3306/oscboard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8;
    username: root
    password: 1q2w3e4r
